create table if not exists agreements (contractid uuid not null, created_date timestamp, duration_conditionuuid uuid, moved_to_block_chain boolean not null, partya varchar(255), partyb varchar(255), payment_conditionuuid uuid, sealed_date timestamp, blockchainid varchar(255), primary key (contractid));
create table if not exists agreements_messages (agreements_contractid uuid not null, messages_messageid uuid not null);
create table if not exists conditions (conditionid uuid not null, condition_description varchar(255), condition_status bytea, proposal_date timestamp, proposing_user varchar(255), contractid uuid, primary key (conditionid));
create table if not exists contact_list (contact_listid uuid not null, contact_list_name varchar(255), ownerid varchar(255), primary key (contact_listid));
create table if not exists evidence (evidence_hash varchar(255) not null, evidence_type bytea, contract_contractid uuid, evidence_url_evidenceid uuid, uploaded_url_evidenceid uuid, user_public_walletid varchar(255), primary key (evidence_hash));
create table if not exists linked_evidence (evidenceid uuid not null, evidence_url varchar(255), evidence_evidence_hash varchar(255), primary key (evidenceid));
create table if not exists messages (messageid uuid not null, message varchar(255), send_date timestamp, contract_contractid uuid, sender_public_walletid varchar(255), primary key (messageid));
create table if not exists message_status (message_statusid uuid not null, read_date timestamp, messagesid_messageid uuid, recipientid_public_walletid varchar(255), primary key (message_statusid));
create table if not exists uploaded_evidence (evidenceid uuid not null, file_mime_type varchar(255), filename varchar(255), evidence_evidence_hash varchar(255), primary key (evidenceid));
create table if not exists "user" (public_walletid varchar(255) not null, alias varchar(255), email varchar(255), primary key (public_walletid));
create table if not exists user_agreements (user_public_walletid varchar(255) not null, agreements_contractid uuid not null);
alter table agreements_messages drop constraint if exists UK_afgb9sc48v1gotdmowm37qupl;
alter table agreements_messages add constraint UK_afgb9sc48v1gotdmowm37qupl unique (messages_messageid);
alter table user_agreements drop constraint if exists UK_svlb2p4l2rqs5pv5r9gybcxj;
alter table user_agreements add constraint UK_svlb2p4l2rqs5pv5r9gybcxj unique (agreements_contractid);
alter table agreements_messages drop constraint if exists FK29002yv87adacnm8ruduqjt48;
alter table agreements_messages add constraint FK29002yv87adacnm8ruduqjt48 foreign key (messages_messageid) references messages;
alter table agreements_messages drop constraint if exists FKrnxrafybfiwwtkhixg7icp7ad;
alter table agreements_messages add constraint FKrnxrafybfiwwtkhixg7icp7ad foreign key (agreements_contractid) references agreements;
alter table conditions drop constraint if exists FK19wl9uu7i5t8vvo1goho80xkj;
alter table conditions add constraint FK19wl9uu7i5t8vvo1goho80xkj foreign key (contractid) references agreements;
alter table evidence drop constraint if exists FKlpioqqatotxodcjc4rw9es0oc;
alter table evidence add constraint FKlpioqqatotxodcjc4rw9es0oc foreign key (contract_contractid) references agreements;
alter table evidence drop constraint if exists FKajyqwe4nut3a9nlsnrg5jkdp6;
alter table evidence add constraint FKajyqwe4nut3a9nlsnrg5jkdp6 foreign key (evidence_url_evidenceid) references linked_evidence;
alter table evidence drop constraint if exists FKkeqst2mm0d8ikev3y3oc5ov6o;
alter table evidence add constraint FKkeqst2mm0d8ikev3y3oc5ov6o foreign key (uploaded_url_evidenceid) references uploaded_evidence;
alter table evidence drop constraint if exists FK98ib2d8e7lq8d96jwrup8u8qf;
alter table evidence add constraint FK98ib2d8e7lq8d96jwrup8u8qf foreign key (user_public_walletid) references "user";
alter table linked_evidence drop constraint if exists FKc3qd7g9wvw4gaxf16fuk3b47h;
alter table linked_evidence add constraint FKc3qd7g9wvw4gaxf16fuk3b47h foreign key (evidence_evidence_hash) references evidence;
alter table messages drop constraint if exists FKtawvl3ujy864wa8yvej43o68b;
alter table messages add constraint FKtawvl3ujy864wa8yvej43o68b foreign key (contract_contractid) references agreements;
alter table messages drop constraint if exists FKpogdllq7macivuimwivkatgaq;
alter table messages add constraint FKpogdllq7macivuimwivkatgaq foreign key (sender_public_walletid) references "user";
alter table message_status drop constraint if exists FK6stq2rkbviclmrtnucd2djw3n;
alter table message_status add constraint FK6stq2rkbviclmrtnucd2djw3n foreign key (messagesid_messageid) references messages;
alter table message_status drop constraint if exists FKtc0v0t1qwbjtgohqvoeacsm0y;
alter table message_status add constraint FKtc0v0t1qwbjtgohqvoeacsm0y foreign key (recipientid_public_walletid) references "user";
alter table uploaded_evidence drop constraint if exists FKi1tejij1ntihpua2py82nddoh;
alter table uploaded_evidence add constraint FKi1tejij1ntihpua2py82nddoh foreign key (evidence_evidence_hash) references evidence;
alter table user_agreements drop constraint if exists FKcai91i3f62212ubvr2ovtee3s;
alter table user_agreements add constraint FKcai91i3f62212ubvr2ovtee3s foreign key (agreements_contractid) references agreements;
alter table user_agreements drop constraint if exists FKd54k8p4t3ln8cl0of3vay2naj;
alter table user_agreements add constraint FKd54k8p4t3ln8cl0of3vay2naj foreign key (user_public_walletid) references "user";