alter table if exists messages drop constraint FKtawvl3ujy864wa8yvej43o68b;
alter table if exists messages drop constraint FKpogdllq7macivuimwivkatgaq;
alter table if exists message_status drop constraint FK6stq2rkbviclmrtnucd2djw3n;
alter table if exists message_status drop constraint FKtc0v0t1qwbjtgohqvoeacsm0y;
alter table if exists uploaded_evidence drop constraint FKi1tejij1ntihpua2py82nddoh;
alter table if exists user_agreements drop constraint FKcai91i3f62212ubvr2ovtee3s;
alter table if exists user_agreements drop constraint FKd54k8p4t3ln8cl0of3vay2naj;
drop table if exists agreements cascade;
drop table if exists agreements_conditions cascade;
drop table if exists agreements_messages cascade;
drop table if exists conditions cascade;
drop table if exists contact_list cascade;
drop table if exists evidence cascade;
drop table if exists linked_evidence cascade;
drop table if exists messages cascade;
drop table if exists message_status cascade;
drop table if exists uploaded_evidence cascade;
drop table if exists "user" cascade;
drop table if exists user_agreements cascade;

create table agreements (contractid uuid not null, created_date timestamp, duration int8, moved_to_block_chain boolean not null, partya varchar(255), partyb varchar(255), sealed_date timestamp, blockchainid varchar(255), primary key (contractid));
create table agreements_conditions (agreements_contractid uuid not null, conditions_conditionid uuid not null);
create table agreements_messages (agreements_contractid uuid not null, messages_messageid uuid not null);
create table conditions (conditionid uuid not null, condition_description varchar(255), condition_status bytea, proposal_date timestamp, proposing_user varchar(255), contract_contractid uuid, primary key (conditionid));
create table contact_list (contact_listid uuid not null, contact_list_name varchar(255), ownerid varchar(255), primary key (contact_listid));
create table evidence (evidence_hash varchar(255) not null, evidence_type bytea, contract_contractid uuid, evidence_url_evidenceid uuid, uploaded_url_evidenceid uuid, user_public_walletid varchar(255), primary key (evidence_hash));
create table linked_evidence (evidenceid uuid not null, evidence_url varchar(255), evidence_evidence_hash varchar(255), primary key (evidenceid));
create table messages (messageid uuid not null, message varchar(255), send_date timestamp, contract_contractid uuid, sender_public_walletid varchar(255), primary key (messageid));
create table message_status (message_statusid uuid not null, read_date timestamp, messagesid_messageid uuid, recipientid_public_walletid varchar(255), primary key (message_statusid));
create table uploaded_evidence (evidenceid uuid not null, file_mime_type varchar(255), filename varchar(255), evidence_evidence_hash varchar(255), primary key (evidenceid));
create table "user" (public_walletid varchar(255) not null, alias varchar(255), email varchar(255), primary key (public_walletid));
create table user_agreements (user_public_walletid varchar(255) not null, agreements_contractid uuid not null);
alter table agreements_conditions add constraint UK_at0qick1msk18s9hsputshyyw unique (conditions_conditionid);
alter table agreements_messages add constraint UK_afgb9sc48v1gotdmowm37qupl unique (messages_messageid);
alter table user_agreements add constraint UK_svlb2p4l2rqs5pv5r9gybcxj unique (agreements_contractid);
alter table agreements_conditions add constraint FKhf094sapg5c1q0yvaw0ufbn66 foreign key (conditions_conditionid) references conditions;
alter table agreements_conditions add constraint FKpi3wqi2xmhofcem0xcga2daff foreign key (agreements_contractid) references agreements;
alter table agreements_messages add constraint FK29002yv87adacnm8ruduqjt48 foreign key (messages_messageid) references messages;
alter table agreements_messages add constraint FKrnxrafybfiwwtkhixg7icp7ad foreign key (agreements_contractid) references agreements;
alter table conditions add constraint FKpr7yy9rgi6w2tupy14o3lpwur foreign key (contract_contractid) references agreements;
alter table evidence add constraint FKlpioqqatotxodcjc4rw9es0oc foreign key (contract_contractid) references agreements;
alter table evidence add constraint FKajyqwe4nut3a9nlsnrg5jkdp6 foreign key (evidence_url_evidenceid) references linked_evidence;
alter table evidence add constraint FKkeqst2mm0d8ikev3y3oc5ov6o foreign key (uploaded_url_evidenceid) references uploaded_evidence;
alter table evidence add constraint FK98ib2d8e7lq8d96jwrup8u8qf foreign key (user_public_walletid) references "user";
alter table linked_evidence add constraint FKc3qd7g9wvw4gaxf16fuk3b47h foreign key (evidence_evidence_hash) references evidence;
alter table messages add constraint FKtawvl3ujy864wa8yvej43o68b foreign key (contract_contractid) references agreements;
alter table messages add constraint FKpogdllq7macivuimwivkatgaq foreign key (sender_public_walletid) references "user";
alter table message_status add constraint FK6stq2rkbviclmrtnucd2djw3n foreign key (messagesid_messageid) references messages;
alter table message_status add constraint FKtc0v0t1qwbjtgohqvoeacsm0y foreign key (recipientid_public_walletid) references "user";
alter table uploaded_evidence add constraint FKi1tejij1ntihpua2py82nddoh foreign key (evidence_evidence_hash) references evidence;
alter table user_agreements add constraint FKcai91i3f62212ubvr2ovtee3s foreign key (agreements_contractid) references agreements;
alter table user_agreements add constraint FKd54k8p4t3ln8cl0of3vay2naj foreign key (user_public_walletid) references "user";
