#will later add rules to package server in container for easier testing and deployment
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./dockerScripts/:/etc/dockerScripts
    environment:
    - POSTGRES_PASSWORD=smartcontractserverdev
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
