package com.savannasolutions.SmartContractVerifierServer.evidence.implementations

import com.savannasolutions.SmartContractVerifierServer.evidence.interfaces.EvidenceFileSystem

class EvidenceFileSystemJIMFSImplementation: EvidenceFileSystem{

}