package com.savannasolutions.SmartContractVerifierServer.user.responses

import com.savannasolutions.SmartContractVerifierServer.common.ResponseStatus

data class AddUserToContactListResponse(val status: ResponseStatus)
