#will later add rules to package server in container for easier testing and deployment
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=smartcontractserverdev
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
