name: CI tests
on: [push]
jobs:
  Integration-and-Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: ls ${{ github.workspace }}
      - run: pwd
      #- run: cd ${{ github.workspace }}/Smart-Contract-Verifier-Server
      #- run: mvn clean install #integration tests
      - run: echo "Unit tests------------------------------------------------------------------------------------------"
