name: CI tests
on: [push]
jobs:
  Integration-and-Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: pwd
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: ls
      - run: cd Smart-Contract-Verifier-Server
      - run: pwd
      #- run: mvn clean install #integration tests
      - run: echo "Unit tests------------------------------------------------------------------------------------------"
