name: CI tests
on: [push]
jobs:
  Integration-and-Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: ls Smart-Contract-Verifier-Server/
      - name: Maven build
        run: mvn clean install -f Smart-Contract-Verifier-Server/pom.xml #integration tests
      - run: echo "Unit tests------------------------------------------------------------------------------------------"
