name: CI tests
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  Integration-and-Unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DBPASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        volumes:
          - Smart-Contract-Verifier-Server/docker/scripts:/docker-entrypoint-initdb.d
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: ls Smart-Contract-Verifier-Server/
      - name: Maven build
        run: mvn clean install -f Smart-Contract-Verifier-Server/pom.xml #integration tests
        env:
          dbuser: ${{ secrets.DBUSER }}
          dbpassword: ${{ secrets.DBPASSWORD }}
          dburl: localhost:5432
          dbgenschema: true

