name: CI tests
on: [push]
jobs:
  Integration-and-Unit-tests:
    runs-on: ubuntu-latest
    services:
      postgresHost:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DBPASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: psql -U postgres postgres -h postgresHost:5432 -f Smart-Contract-Verifier-Server/docker/scripts/init.sql
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: ls Smart-Contract-Verifier-Server/
      - name: Maven build
        run: mvn clean install -f Smart-Contract-Verifier-Server/pom.xml #integration tests
        env:
          dbuser: ${{ secrets.DBUSER }}
          dbpassword: ${{ secrets.DBPASSWORD }}
          dburl: postgres
          dbgenschema: true