name: CI tests
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
  Integration-and-Unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: ls #integration tests
      - run: mvn clean install -f /Smart-Contract-Verifier-Server/pom.xml #integration tests
      - run: echo "Unit tests------------------------------------------------------------------------------------------"
