name: CI tests
on: [push]
jobs:
  Integration-and-Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: cd ${{ github.workspace }}/..
      - run: pwd
      - run: cd Smart-Contract-Verifier-Server
      - run: mvn clean install #integration tests
      - run: echo "Unit tests------------------------------------------------------------------------------------------"
