name: CI tests
on: [push]
jobs:
  Integration-and-Unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - run: psql postgres -f Smart-Contract-Verifier-Server/docker/scripts/init.sql
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: echo "Integration tests-----------------------------------------------------------------------------------"
      - run: ls Smart-Contract-Verifier-Server/
      - name: Maven build
        run: mvn clean install -f Smart-Contract-Verifier-Server/pom.xml #integration tests
        env:
          dbuser: ${{ secrets.DBUSER }}
          dbpassword: ${{ secrets.DBPASSWORD }}
          dburl: localhost:5432
          dbgenschema: true

